# Generated by Django 3.2.16 on 2024-10-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='text',
            new_name='description',
        ),
    ]
